### ISSUE TITLE
Include typescript

### ISSUE THREAD

**Issue by Toflar** [contao-components/ace#1]
Given the fact that an increasing number of projects use typescript instead of JavaScript, I think it would be great if we could include the TS mode too :)

See https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/typescript.js

**Comment by leofeyer** [comment]
Added in 03ff66a5692bd03470fdf315a31ba01ee8976d3d.

**Comment by leofeyer** [comment]
Complementary PR: https://github.com/contao/contao/pull/3911
